### PR TITLE
Hacktoberfest: Add Python Armstrong number checker program

### PR DESCRIPTION
**Pull request by techyminati**

### CODE REVIEW

**Comment by techyminati** [comment]
@khageshwor Repository Maintainer, Kindly Review & Merge

**Comment by tausiq2003** [comment]
can I contribute

**Comment by tausiq2003** [comment]
Can I contribute

**Comment by khageshwor** [comment]
@tausiq2003 yes

**Comment by tausiq2003** [comment]
ok sorry for being late what I will do add some file or modify them

**Pull request merged**
